### ISSUE TITLE
meta tracking issue for AutoRIFT v2.0.0

### ISSUE THREAD

**Issue by jhkennedy** [nasa-jpl/autoRIFT#102]
AutoRIFT was last released nearly two years ago with v1.5.0 in Nov. of 2022 and has seen quite a few changes since then:
https://github.com/nasa-jpl/autoRIFT/compare/v1.5.0..master

Likewise, we've had a number of questions about using autoRIFT in issues, Gitter, emails, and personal communication, as well as my own experience, that indicate that there are some sorely needed improvements to the usability of the code. Therefore, I propose we move towards version 2.0.0, primarily focused on usability, code quality, and testing improvements.

Let's use this issue to group and track the overall issues and features we should include in a v2.0.0 release.

> [!IMPORTANT]
> Please try to keep discussion about specific tasks in their associated Issue or PR to keep things organized. If a task doesn't have an issue or pr yet, please open an issue or pr.

## Housekeeping

Before running headlong down this path, we should resolve and clean up some old issues and release the current changes.

- [x] Review and merge https://github.com/nasa-jpl/autoRIFT/pull/101
- [x] Finish the S1 correction workflow by bringing in any hyp3-autorift change to #78 and merging it
- [x] #103
- [x] https://github.com/nasa-jpl/autoRIFT/issues/97
- [x] Release v1.6.0 with all of the above to clear the path for v2

## Packaging and distribution

- [ ] build extensions with scikit-build-core or similar modern build tools
- [ ] convert setup.py to pyproject.toml
- [ ] list actual package dependencies in pyproject.toml
- [ ] improve package metadata in pyproject.toml
- [ ] state supported python versions in pyproject.toml
- [ ] test*.py scripts, topsinsar_filename.py, and netcdf_output.py scripts are not distributed with the package

## Development practices

- [ ] #104

## Documentation

- [ ] `python setup.py install` is deprecated; use pip as is done in the conda-forge build
- [ ] add figures/diagrams from https://github.com/nasa-jpl/autoRIFT/issues/62 to the docs

**Comment by jhkennedy** [comment]
With the release of v1.6.0 and the pending release of v2.0.0 using an ISCE3-based radar workflow, I'm going to close this issue and open a v3.0.0 tracking issue with the remaining work.
